openapi: 3.0.3
info:
  description: REST API definitions for Taskmaster
  title: Taskmaster
  version: "0"
servers:
- description: API server
  url: /api
paths:
  /v1/tasks:
    get:
      operationId: getTasks
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ListProjectsResponse'
          description: OK
      summary: Get tasks
components:
  schemas:
    LogConfig:
      properties:
        compression:
          type: string
      required:
      - compression
      type: object
    Task:
      properties:
        log:
          $ref: '#/components/schemas/LogConfig'
        name:
          type: string
        script:
          type: string
      required:
      - name
      - script
      - log
      type: object
    ListProjectsResponse:
      properties:
        tasks:
          items:
            $ref: '#/components/schemas/Task'
          type: array
      required:
      - tasks
      type: object
